version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    reviewers:
      - "thepieterdc"
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: "/"
    reviewers:
      - "thepieterdc"
    schedule:
      interval: daily