name: Build

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  go:
    name: Build Go code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download libpostal
        run: git clone https://github.com/openvenues/libpostal /tmp/libpostal

      - name: Install libpostal
        run: |
          mkdir /tmp/libpostaldata
          cd /tmp/libpostal
          ./bootstrap.sh && ./configure --datadir=/tmp/libpostaldata
          sudo make -j && sudo make install && sudo ldconfig

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - run: go build -v .

      - run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload the coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
