name: Build

on:
  push:

jobs:
  go:
    name: Build Go code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Download libpostal
        run: git clone https://github.com/openvenues/libpostal /tmp/libpostal

      - name: Install libpostal
        run: |
          mkdir /tmp/libpostaldata
          cd /tmp/libpostal
          ./bootstrap.sh && ./configure --datadir=/tmp/libpostaldata
          sudo make -j && sudo make install && sudo ldconfig

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - run: go build -v .